
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diemme?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: diemme
    password: diemme
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### MYUNIVAQ PROPERTIES ###############
###############################################

